# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_auto_20160717_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
