# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_gallery_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='artist',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='gallery',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.Gallery'),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
