# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_auto_20160720_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='total_rankers',
            field=models.IntegerField(default=0),
        ),
    ]
