# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_auto_20160720_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='total_raters',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='rating',
            field=models.IntegerField(default=0.0),
        ),
    ]
