# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0011_auto_20160726_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.ArtistProfile'),
        ),
    ]
