# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_auto_20160726_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='avatar',
            field=models.ImageField(default='/art/placeholder.jpg', upload_to=''),
        ),
    ]
